# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---

# See: https://github.com/puppetlabs/puppetlabs_spec_helper#fixtures-examples
fixtures:
  # Dependencies from Puppet Forge
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.25.1"
    epel:
      repo: "puppet/epel"
      ref: "3.0.1"
    yumrepo:
      repo: "puppetlabs/yumrepo_core"
      ref: "1.0.7"
